# Workflow para compilar e implantar um projeto Angular no GitHub Pages
name: Deploy Angular application to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de Build (Compilação)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Versão estável do Node recomendada para Angular moderno
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build do Angular
        run: npm run build -- --configuration=production

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          # ATENÇÃO: No Angular, a pasta gerada fica dentro de 'dist/[nome-do-seu-projeto]/browser' (Angular 17+)
          # ou apenas 'dist/[nome-do-seu-projeto]' (Angular 16 para baixo).
          # Verifique no seu projeto local qual pasta é criada dentro de 'dist' após dar um 'npm run build' e ajuste a linha abaixo:
          path: './dist/age-calculator-app-main/browser' 

  # Job de Implantação (Deployment)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
