name: Deploy Angular application to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true # Mudei para true para cancelar execuções antigas e evitar duplicidade

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build do Angular
        run: npm run build -- --configuration=production --base-href=/age-calculator-app-main/

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          # Lembre-se de ajustar este caminho para o do seu projeto!
          path: './dist/age-calculator-app-main-ang/browser' 

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Forçando a v4 que casa perfeitamente com o upload v3
